# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

mvndrawC <- function(mu, sig) {
    .Call('_MFVART_mvndrawC', PACKAGE = 'MFVART', mu, sig)
}

#' @export
carterkohn <- function(y, Z, Ht, Qt, m, p, t, B0, V0) {
    .Call('_MFVART_carterkohn', PACKAGE = 'MFVART', y, Z, Ht, Qt, m, p, t, B0, V0)
}

alphahelper <- function(y, Z, Btdraw) {
    .Call('_MFVART_alphahelper', PACKAGE = 'MFVART', y, Z, Btdraw)
}

sigmahelper1 <- function(Atdraw, M) {
    .Call('_MFVART_sigmahelper1', PACKAGE = 'MFVART', Atdraw, M)
}

sigmahelper2 <- function(capAt, yhat, qs, ms, u2s, Sigtdraw, Zs, Wdraw, sigma_prmean, sigma_prvar) {
    .Call('_MFVART_sigmahelper2', PACKAGE = 'MFVART', capAt, yhat, qs, ms, u2s, Sigtdraw, Zs, Wdraw, sigma_prmean, sigma_prvar)
}

#' @export
sigmahelper4 <- function(y2, qs, ms, u2s, Sigtdraw, Zs, Wdraw, sigma_prmean, sigma_prvar) {
    .Call('_MFVART_sigmahelper4', PACKAGE = 'MFVART', y2, qs, ms, u2s, Sigtdraw, Zs, Wdraw, sigma_prmean, sigma_prvar)
}

sigmahelper3 <- function(capAt, sigt) {
    .Call('_MFVART_sigmahelper3', PACKAGE = 'MFVART', capAt, sigt)
}

getvc <- function(Ht) {
    .Call('_MFVART_getvc', PACKAGE = 'MFVART', Ht)
}

makeregs_fcC <- function(ydat, p) {
    .Call('_MFVART_makeregs_fcC', PACKAGE = 'MFVART', ydat, p)
}

mz <- function(n) {
    .Call('_MFVART_mz', PACKAGE = 'MFVART', n)
}

meye <- function(n) {
    .Call('_MFVART_meye', PACKAGE = 'MFVART', n)
}

vechC <- function(x) {
    .Call('_MFVART_vechC', PACKAGE = 'MFVART', x)
}

getfcsts <- function(Bt0, At0, Sigt0, Qdraw, Sdraw, Wdraw, ydat, nf, p) {
    .Call('_MFVART_getfcsts', PACKAGE = 'MFVART', Bt0, At0, Sigt0, Qdraw, Sdraw, Wdraw, ydat, nf, p)
}

wishdrawC <- function(h, n) {
    .Call('_MFVART_wishdrawC', PACKAGE = 'MFVART', h, n)
}

makeregs2_fcC <- function(dat, p) {
    .Call('_MFVART_makeregs2_fcC', PACKAGE = 'MFVART', dat, p)
}

matmult <- function(x, nt) {
    .Call('_MFVART_matmult', PACKAGE = 'MFVART', x, nt)
}

varfcst <- function(b, sig, y, nf) {
    .Call('_MFVART_varfcst', PACKAGE = 'MFVART', b, sig, y, nf)
}

